### PR TITLE
pull from docker image with docker file

### PR DESCRIPTION
**Pull request by Major2000**
Incase one wishes to pull the image from docker these are basic settings I tried this my self

### CODE REVIEW

**Comment by matthewDDennis** [comment]
Could you please explain why this should be included in the master branch.
A Docker Compose tends to be specific to the overall deployment of services for a solution that includes one or more docker images.  As such is depends on the environment, the other docker images, ports to expose, etc.
One Compose file won't fit everything.
However, if you can explain what and why you are doing things in the compose file, we could include it as an example integration, which would be great.

**Comment by Major2000** [comment]
Okay, Yes sir!
The docker compose file is included for deployment purposes!. It can be required to set up the AI server on a specific cloud platform, such as `Okteto` (the one I used). Developers who fork the repository and include the docker compose file will have an example of how to quickly deploy the server to the cloud platform, which will be very useful for people who might require this but are unsure of how to set 
it up.

On Okteto, I installed the AI Server, and I utilized the end point to access the services. The cloud platform reads the `compose file` and pulls the image for deployment.



Utilizing the end point



Working perfect!



Hope this is enough explanation, Thanks Sir!

**Comment by matthewDDennis** [comment]
It would be great if you could write this up as an article and submit it to CodeProject.com.

**Comment by ChrisMaunder** [comment]
I'm closing this because we have multiple docker compose files now part of the larger project, but thanks for prompting us to get this done.

**Pull request closed without merging**
